name = "Steel Ball Run"
author = "TheTaciturnOne, AmyMialee"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "b99da80b0887282f268c78b35ee474da28dd9489d1fb39ff10f7199ab4bab709"

[versions]
fabric = "0.16.14"
minecraft = "1.21.1"

[options]
acceptable-game-versions = ["1.21"]
