name = "Steel Ball Run"
author = "TheTaciturnOne, AmyMialee"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "67e08a709062a5c29cbed4878bbb110530f218e88aea17dfcac84c76d668ba0c"

[versions]
fabric = "0.16.14"
minecraft = "1.21.1"

[options]
acceptable-game-versions = ["1.21"]
