name = "Steel Ball Run"
author = "TheTaciturnOne, AmyMialee"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "be4f62fc03fb5cc0aa4d780bb46df204a3e08b0972ecdc1217cc4019358f62ad"

[versions]
fabric = "0.16.14"
minecraft = "1.21.1"

[options]
acceptable-game-versions = ["1.21"]
