name = "Steel Ball Run"
author = "TheTaciturnOne, AmyMialee"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "d560bbbea48c8a65429aa0bf62c618bb5c35a823344799f6df027137b2e8a01a"

[versions]
fabric = "0.16.14"
minecraft = "1.21.1"

[options]
acceptable-game-versions = ["1.21"]
