name = "Steel Ball Run"
author = "TheTaciturnOne, AmyMialee"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "8e94cf9b908698f7fc043db6cbdf9eb638ec3e56803fbcb21409881cc438901e"

[versions]
fabric = "0.16.14"
minecraft = "1.21.1"
